# Generated by Django 4.2.30 on 2026-06-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('internal_username', models.CharField(max_length=64, unique=True, verbose_name='内部用户名')),
                ('unionid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信 unionid')),
                ('mp_openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='小程序 openid')),
                ('web_openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Web openid')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, max_length=512, null=True, verbose_name='头像')),
                ('is_staff', models.BooleanField(default=False, verbose_name='平台管理员')),
                ('is_super_staff', models.BooleanField(default=False, verbose_name='预置超级管理员')),
                ('staff_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('shop_status', models.SmallIntegerField(choices=[(0, '普通用户'), (1, '待审核'), (2, '已入驻'), (3, '审核驳回'), (4, '已封禁')], default=0, verbose_name='商家状态')),
                ('shop_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联商家 ID')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('last_login_platform', models.CharField(blank=True, choices=[('mini_program', '小程序'), ('web', 'Web')], default='', max_length=16, verbose_name='最近登录平台')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_staff_users', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='AuthLoginTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=64, unique=True, verbose_name='票据')),
                ('status', models.SmallIntegerField(choices=[(0, '待扫码'), (1, '已扫码待确认'), (2, '已确认'), (3, '已过期')], default=0, verbose_name='状态')),
                ('scan_openid', models.CharField(blank=True, max_length=64, null=True, verbose_name='扫码 openid')),
                ('scan_unionid', models.CharField(blank=True, max_length=64, null=True, verbose_name='扫码 unionid')),
                ('redirect_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转路径')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端 IP')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_tickets', to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '扫码登录票据',
                'verbose_name_plural': '扫码登录票据',
                'db_table': 'auth_login_ticket',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='auth_login__status_9c6113_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['shop_status'], name='user_shop_st_9f3150_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['shop_id'], name='user_shop_id_c5f340_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='user_is_staf_3c0a45_idx'),
        ),
    ]
