# Generated by Django 4.2.30 on 2026-06-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_usershopvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('thread_status', models.SmallIntegerField(choices=[(1, '未读'), (2, '已读未回复'), (3, '已回复')], default=1, verbose_name='会话状态')),
                ('unread_count_user', models.PositiveIntegerField(default=0, verbose_name='用户未读数')),
                ('unread_count_shop', models.PositiveIntegerField(default=0, verbose_name='商家未读数')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('last_message_preview', models.CharField(blank=True, max_length=100, null=True, verbose_name='消息预览')),
                ('user_read_at', models.DateTimeField(blank=True, null=True, verbose_name='用户已读时间')),
                ('shop_read_at', models.DateTimeField(blank=True, null=True, verbose_name='商家已读时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='bikes.bike', verbose_name='车源')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='shops.shop', verbose_name='商家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '咨询会话',
                'verbose_name_plural': '咨询会话',
                'db_table': 'message_thread',
            },
        ),
        migrations.CreateModel(
            name='MessageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.SmallIntegerField(choices=[(1, '用户'), (2, '商家'), (3, '系统')], verbose_name='发送方')),
                ('content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_items', to='shops.shop', verbose_name='商家')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messagethread', verbose_name='会话')),
            ],
            options={
                'verbose_name': '会话消息',
                'verbose_name_plural': '会话消息',
                'db_table': 'message_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['shop', 'thread_status', '-last_message_at'], name='message_thr_shop_id_5651d2_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['user', '-last_message_at'], name='message_thr_user_id_95fa5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together={('user', 'bike')},
        ),
        migrations.AddIndex(
            model_name='messageitem',
            index=models.Index(fields=['thread', 'created_at'], name='message_ite_thread__b760c5_idx'),
        ),
        migrations.AddIndex(
            model_name='messageitem',
            index=models.Index(fields=['shop'], name='message_ite_shop_id_2abd48_idx'),
        ),
    ]
