# Generated by Django 4.2.30 on 2026-06-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.SmallIntegerField(choices=[(1, '个人商户'), (2, '企业商户')], verbose_name='入驻类型')),
                ('contact_name', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='经营地址')),
                ('main_models', models.CharField(blank=True, default='', max_length=50, verbose_name='主营车型')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='入驻说明')),
                ('wechat_qrcode', models.CharField(max_length=512, verbose_name='微信二维码')),
                ('qualification_photo', models.CharField(blank=True, max_length=512, null=True, verbose_name='资质照片')),
                ('application_status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已驳回')], default=1, verbose_name='申请状态')),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='驳回原因')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '商家入驻申请',
                'verbose_name_plural': '商家入驻申请',
                'db_table': 'shop_application',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user'], name='shop_applic_user_id_fcf603_idx'), models.Index(fields=['application_status'], name='shop_applic_applica_62575a_idx'), models.Index(fields=['-applied_at'], name='shop_applic_applied_1f9526_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商家名称')),
                ('shop_type', models.SmallIntegerField(choices=[(1, '个人商户'), (2, '企业商户')], verbose_name='入驻类型')),
                ('contact_name', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='经营地址')),
                ('main_models', models.CharField(blank=True, default='', max_length=50, verbose_name='主营车型')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='商家简介')),
                ('avatar', models.CharField(blank=True, max_length=512, null=True, verbose_name='店铺头像')),
                ('wechat_qrcode', models.CharField(max_length=512, verbose_name='微信二维码')),
                ('qualification_photo', models.CharField(blank=True, max_length=512, null=True, verbose_name='资质照片')),
                ('shop_status', models.SmallIntegerField(choices=[(2, '正常'), (4, '封禁')], default=2, verbose_name='商家状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核通过时间')),
                ('banned_at', models.DateTimeField(blank=True, null=True, verbose_name='封禁时间')),
                ('ban_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='封禁原因')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='商家主账号')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'shop',
                'indexes': [models.Index(fields=['shop_status'], name='shop_shop_st_fb8884_idx')],
            },
        ),
    ]
