# Generated by Django 4.2.30 on 2026-06-29 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShopVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='访问次数')),
                ('last_visited_at', models.DateTimeField(auto_now=True, verbose_name='最近访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次访问时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shops.shop', verbose_name='商家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_visits', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商家访问记录',
                'verbose_name_plural': '商家访问记录',
                'db_table': 'user_shop_visit',
                'indexes': [models.Index(fields=['user', '-last_visited_at'], name='user_shop_v_user_id_ce5043_idx')],
                'unique_together': {('user', 'shop')},
            },
        ),
    ]
