# Generated by Django 4.2.30 on 2026-06-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_usershopvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(blank=True, null=True, verbose_name='品牌 ID')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌名称')),
                ('model', models.CharField(max_length=64, verbose_name='车型')),
                ('year', models.SmallIntegerField(verbose_name='上牌年份')),
                ('register_date', models.DateField(blank=True, null=True, verbose_name='上牌日期')),
                ('displacement', models.CharField(max_length=16, verbose_name='排量')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='行驶里程')),
                ('transfer_count', models.PositiveSmallIntegerField(default=0, verbose_name='过户次数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='售价')),
                ('can_transfer', models.BooleanField(default=True, verbose_name='是否可过户')),
                ('negotiable', models.BooleanField(default=True, verbose_name='是否可议价')),
                ('engine_status', models.CharField(max_length=500, verbose_name='发动机状态')),
                ('suspension_status', models.CharField(max_length=500, verbose_name='减震状态')),
                ('brake_status', models.CharField(max_length=500, verbose_name='刹车状态')),
                ('electrical_status', models.CharField(max_length=500, verbose_name='电控状态')),
                ('frame_status', models.CharField(max_length=500, verbose_name='车架状态')),
                ('modification', models.CharField(max_length=500, verbose_name='改装明细')),
                ('defects', models.CharField(max_length=500, verbose_name='瑕疵说明')),
                ('maintenance', models.CharField(max_length=500, verbose_name='维保记录')),
                ('delivery_method', models.CharField(blank=True, default='', max_length=64, verbose_name='交付方式')),
                ('fee_note', models.CharField(blank=True, default='', max_length=200, verbose_name='费用说明')),
                ('after_sale', models.CharField(blank=True, default='', max_length=200, verbose_name='售后说明')),
                ('cover_image', models.CharField(max_length=512, verbose_name='封面图')),
                ('bike_status', models.SmallIntegerField(choices=[(1, '在售'), (2, '已售'), (3, '商家下架'), (4, '违规下架')], default=1, verbose_name='车辆状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次上架时间')),
                ('off_shelf_at', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('force_off_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='违规下架原因')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('force_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_off_bikes', to=settings.AUTH_USER_MODEL, verbose_name='违规操作人')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='shops.shop', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '车源',
                'verbose_name_plural': '车源',
                'db_table': 'bike',
            },
        ),
        migrations.CreateModel(
            name='BikeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.SmallIntegerField(choices=[(1, '封面'), (2, '展示图'), (3, '车况图'), (4, '视频')], verbose_name='媒体类型')),
                ('url', models.CharField(max_length=512, verbose_name='媒体 URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='视频时长')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='bikes.bike', verbose_name='车源')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_media', to='shops.shop', verbose_name='商家')),
            ],
            options={
                'verbose_name': '车源媒体',
                'verbose_name_plural': '车源媒体',
                'db_table': 'bike_media',
                'indexes': [models.Index(fields=['bike', 'media_type', 'sort_order'], name='bike_media_bike_id_e96736_idx'), models.Index(fields=['shop'], name='bike_media_shop_id_c6ca03_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['shop', 'bike_status', '-published_at'], name='bike_shop_id_14294e_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['shop', 'is_deleted'], name='bike_shop_id_5731f4_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['price'], name='bike_price_e3c13d_idx'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['year'], name='bike_year_095f47_idx'),
        ),
    ]
