# Generated by Django 4.2.30 on 2026-06-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='品牌名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'brand',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='车型名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '车型',
                'verbose_name_plural': '车型',
                'db_table': 'brand_model',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['brand'], name='brand_model_brand_i_50d37b_idx')],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
